language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - oraclejdk6
notifications:
  email: false
  slack:
    secure: G9DuGi6VAERi3Am5yoZeuLZHNIpvdyRkjMlGDsXGO7yvN+CN1284YeEOuhgAQSUuq7ccRdCggnP9kI5ncgeDfbEhAf4WgXvZB/Z5oIe+Dpdw6zOIVbACIZ3SwOH7/FiJDU6rODoL3KMRpGSm4rn2qYXPdrmJvSOlUvztLIB1RVs=
